### ISSUE TITLE
Run parents

### ISSUE THREAD

**Issue by Crisfole** [apsislabs/orca#9]
If you have the following setup:

```
app.registerAction('foo', fooBase);
app.registerAction('foo.bar', fooBar);
```

And you call `app.run('foo.bar')`. It should also call fooBase.

**Comment by wkirby** [comment]
I think this is directionally the opposite of our current implementation. When you call run, we run everything in the namespace you specify and _down_. This allows you to run everything that is in the current namespace, or a subset of that namespace.
